### ISSUE TITLE
compile_native_es failed

### ISSUE THREAD

**Issue by xiaohuidexinge** [chrishumphreys/LIbGDX-Pi#1]
I found your <LibGDX on Raspberry Pi> is very useful for me, but when following the steps , i run into some problem.While running ant compile_native_es , it reports error: extgl_egl.h:70: unknown type 'PFNEGLLOCKSURFACEKHRPROC'. any tips on this? thank you very much. :)

**Comment by chrishumphreys** [comment]
Hi xiaohuidexinge,

I've noticed this too with later versions of raspbian. The code compiles fine on the http://downloads.raspberrypi.org/raspbian/images/2012-10-28-wheezy-raspbian/ release but fails on the latest version (and perhaps on interim releases too).

The missing type definitions are included in /opt/vc/include/EGL/eglext.h on the older version and absent on the latest version!

Interestingly the headers on my older raspbian release are "Copyright (c) 2007-2010 The Khronos Group Inc." where the latest raspbian release is "Copyright (c) 2007-2009 The Khronos Group Inc."

I'll try and do some digging to find out why these header files are different, and it appears downgraded...

**Comment by chrishumphreys** [comment]
A bit more info of the packages installed on the old and new Raspbian:

New raspbian (doesn't compile)

dpkg -s libraspberrypi-dev
Package: libraspberrypi-dev
Status: install ok installed
Priority: extra
Section: libdevel
Installed-Size: 2831
Maintainer: Alex Bradbury asb@asbradbury.org
Architecture: armhf
Source: raspberrypi-firmware
Version: 1.20130902-1
Depends: libraspberrypi0 (= 1.20130902-1)
Description: EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
 This package contains headers and other development files for implementations
 of EGL, OpenGL ES, OpenVG, OpenWF Composition, and others for the Raspberry
 Pi's VideoCore IV multimedia processor.
Homepage: https://github.com/raspberrypi/firmware

Old raspbian (works)

dpkg -s libraspberrypi-dev
Package: libraspberrypi-dev
Status: install ok installed
Priority: extra
Section: libdevel
Installed-Size: 2568
Maintainer: Alex Bradbury asb@asbradbury.org
Architecture: armhf
Source: raspberrypi-firmware
Version: 1.20121025-1
Depends: libraspberrypi0 (= 1.20121025-1)
Description: EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
 This package contains headers and other development files for implementations
 of EGL, OpenGL ES, OpenVG, OpenWF Composition, and others for the Raspberry
 Pi's VideoCore IV multimedia processor.
Homepage: https://github.com/raspberrypi/firmware

**Comment by chrishumphreys** [comment]
It appears to have been this commit to the raspberrypi firmware project which took away the definitions we need:

https://github.com/raspberrypi/firmware/commit/855e997fb4588ef47ab6b4db23b47e42043f7527

**Comment by xiaohuidexinge** [comment]
hi chrishumphreys
it's very nice of you to dig into this problem, i still did not pass the compiling, so i choose to use your packages under pi-gdx-invaders you compiled before, and it still works fine~~~.:)

**Comment by chrishumphreys** [comment]
hi xiaohuidexinge,

Glad that worked for you!

I've managed to get lwjgl to compile again on latest Raspbian and have updated the instructions.

thanks for pointing this issue out
